make branch
crane93/Issue-Maker pull request #12
Opened 2019-05-22 15:34 UTC by crane93

### このPRですべきこと
- [ ] Spring BootのビューをJSPですること

### このPRが処理するissue
#11 

### 説明
- すでにセッティングされているGradleを活用してJSPを動作してみた
- 苦労したこと 
  - #10 作っておいたJAVAのメインクラスと今度のメインクラスがかぶっちゃって
　Spring Bootが動かなった
![고장_cr](https://user-images.githubusercontent.com/44425582/58187348-8d3c1b80-7cf1-11e9-9159-728677ed01c5.png)
  - 解決方法：gradle initとgradle wrapperを合わせ、メインクラスを一つにした

### ステータス
* END

### 結果イメージ
![스프링부트jsp](https://user-images.githubusercontent.com/44425582/58187601-0471af80-7cf2-11e9-8fca-158105d510d9.png)

---
### 이 PR에서 할 일
- [ ] 스프링부트의 뷰페이지를 JSP로 하기

### 이 PR 처리하는 issue
#11 

### 설명
- 이미 설정해놓은 Gradle위에서 JSP를 동작해보았다
- 겪은 문제점
  - #10 에서 썼던 JAVA 메인클래스와 이번 실습에서 적은 메인클래스가 문제가되어 Spring Boot가 동작하지 않았다
![고장_cr](https://user-images.githubusercontent.com/44425582/58187812-7b0ead00-7cf2-11e9-8dc6-53df30542bb1.png)

  - 해결방법: Gradle init과 Gradle wrapper를 잘 맞추고 메인클래스를 하나로 만들었다

### 진행상황
* END

### 구현이미지
![스프링부트jsp](https://user-images.githubusercontent.com/44425582/58187847-895cc900-7cf2-11e9-9bcd-9ed259a4787a.png)

2019-05-23 03:06 UTC, cheekykorkind requested changes
개선 제안 입니다.
-  PR(풀리퀘스트)의 제목을 작업내용이 드러나도록 수정 부탁드립니다.
- 레뷰어와 어사이니를 설정부탁드립니다.
![needToSet](https://user-images.githubusercontent.com/22050468/58223063-3830f180-7d53-11e9-89ed-5c0482e47c63.PNG)


참고 사항입니다.
- 프라이베이트 아이피(192.168.~~~~~)은 가릴 필요 없습니다!

2019-05-23 23:49 UTC, cheekykorkind approved these changes
머지합시다!!

2019-05-24 00:18 UTC, merged

2019-05-24 00:27 UTC, crane93 commented
> * 프라이베이트 아이피(192.168.~~~~~)은 가릴 필요 없습니다!

왜 가릴필요 없어요?  전에 리눅스 화면 캡쳐해서 올렸을땐 안된다고 했는데 아이피는 왜 안되여?

> 😮

2019-05-24 11:01 UTC, cheekykorkind commented
저번스샷에는 노트북 바로가기나 크롬 즐겨찾기 같은 개인적인게 다 드러나서 가리면 좋겠ㄷ고 생각했습니다.
프라이베이트 아이피는 누구나 사용하는 아이피고 그거 알아봐야해킹도 안되니 가릴필요 없다규 생각했습다

2019년 5월 24일 (금) 오전 9:27, Yuri KIM <notifications@github.com>님이 작성:

>
>    - 프라이베이트 아이피(192.168.~~~~~)은 가릴 필요 없습니다!
>
> 왜 가릴필요 없어요? 전에 리눅스 화면 캡쳐해서 올렸을땐 안된다고 했는데 아이피는 왜 안되여?
>
> 😮
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/crane93/Issue-Maker/pull/12?email_source=notifications&email_token=AFIHNJE46656TDRHXAUT2LDPW4Y6LA5CNFSM4HOVSBO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWD2UUQ#issuecomment-495430226>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFIHNJEGYTOR6U7YBLEJUKTPW4Y6LANCNFSM4HOVSBOQ>
> .
>